name: Auto Comment
on: 
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - closed
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name : Auto comment on Issues opened
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            Thank you @{{ author }}, for raising this issue! <br>
            
            Your input is valuable in improving our project.
            Please ensure you provide more context about the issue. We will review it as soon as possible.
          

      - name: Auto Comment on Pull Request Opened
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            Hello ðŸ‘‹ @{{ author }}, I hope you're doing well! <br>

            Thank you for raising your pull request and contributing to ResourceHub ðŸŽ‰.
            Please ensure that you've followed our [contributing guidelines](https://github.com/jfmartinz/ResourceHub/blob/main/CONTRIBUTING.md) and the PR template. 
            
            We will review it as soon as possible.

            
      - name: Auto comment on PR merged
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestMerged: |
            Congratulations @{{ author }}! ðŸŽ‰ Your pull request has been merged. <br> 
            
            Thanks for your contribution! ðŸ˜Š
